name: 'Publish Docker Images'
description: 'Publishes the Docker Images'
inputs:
  dockerfile:
    description: 'Dockerfile to build'
    required: true
  tag:
    description: 'The Tag for the Docker image'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PACKAGE_SECRET }}
      
    - name: Prepare env
      run: |
        echo "BUILD_VERSION=${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ID}" >> $GITHUB_ENV
      shell: bash

    - name: Build & Push to Package Repositories
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./docker/${{ inputs.dockerfile }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        build-args: VERSION=${{ env.BUILD_VERSION }}
        tags: |
            ${{ secrets.DOCKER_USERNAME }}/peloton-to-garmin:${{ inputs.tag }}
            ghcr.io/${{ github.repository_owner }}/peloton-to-garmin:${{ inputs.tag }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      shell: bash
