version: "3.5"

services:
  p2g:
    container_name: p2g
    image: philosowaffle/peloton-to-garmin:fitvLatest
    volumes:
      # You may need to grant read/write permissions on the following.
      - ./config:/app/config
      - ./output:/app/output