version: "3.5"
   
services:
  p2g:
    container_name: p2g
    image: philosowaffle/peloton-to-garmin:fitvLatest
    volumes:
      - ./configuration.local.json:/opt/app/configuration.local.json
      - ./output:/output
