#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Mode used for Read Operations
    /// </summary>
    public enum DecodeMode
    {
        /// <summary>
        /// Indicates that file contains valid Header and CRC data
        /// </summary>
        Normal,

        /// <summary>
        /// Indicates that the Stream Contains a Header that is Corrupt
        /// </summary>
        InvalidHeader,

        /// <summary>
        /// Indicates that the Stream does not contain a Header or CRC
        /// </summary>
        DataOnly
    }
}
