#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.105Release
// Tag = production/release/21.105.00-0-gdc65d24
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile CardioExerciseName type as a class
    /// </summary>
    public static class CardioExerciseName 
    {
        public const ushort BobAndWeaveCircle = 0;
        public const ushort WeightedBobAndWeaveCircle = 1;
        public const ushort CardioCoreCrawl = 2;
        public const ushort WeightedCardioCoreCrawl = 3;
        public const ushort DoubleUnder = 4;
        public const ushort WeightedDoubleUnder = 5;
        public const ushort JumpRope = 6;
        public const ushort WeightedJumpRope = 7;
        public const ushort JumpRopeCrossover = 8;
        public const ushort WeightedJumpRopeCrossover = 9;
        public const ushort JumpRopeJog = 10;
        public const ushort WeightedJumpRopeJog = 11;
        public const ushort JumpingJacks = 12;
        public const ushort WeightedJumpingJacks = 13;
        public const ushort SkiMoguls = 14;
        public const ushort WeightedSkiMoguls = 15;
        public const ushort SplitJacks = 16;
        public const ushort WeightedSplitJacks = 17;
        public const ushort SquatJacks = 18;
        public const ushort WeightedSquatJacks = 19;
        public const ushort TripleUnder = 20;
        public const ushort WeightedTripleUnder = 21;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

