#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.105Release
// Tag = production/release/21.105.00-0-gdc65d24
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile ChopExerciseName type as a class
    /// </summary>
    public static class ChopExerciseName 
    {
        public const ushort CablePullThrough = 0;
        public const ushort CableRotationalLift = 1;
        public const ushort CableWoodchop = 2;
        public const ushort CrossChopToKnee = 3;
        public const ushort WeightedCrossChopToKnee = 4;
        public const ushort DumbbellChop = 5;
        public const ushort HalfKneelingRotation = 6;
        public const ushort WeightedHalfKneelingRotation = 7;
        public const ushort HalfKneelingRotationalChop = 8;
        public const ushort HalfKneelingRotationalReverseChop = 9;
        public const ushort HalfKneelingStabilityChop = 10;
        public const ushort HalfKneelingStabilityReverseChop = 11;
        public const ushort KneelingRotationalChop = 12;
        public const ushort KneelingRotationalReverseChop = 13;
        public const ushort KneelingStabilityChop = 14;
        public const ushort KneelingWoodchopper = 15;
        public const ushort MedicineBallWoodChops = 16;
        public const ushort PowerSquatChops = 17;
        public const ushort WeightedPowerSquatChops = 18;
        public const ushort StandingRotationalChop = 19;
        public const ushort StandingSplitRotationalChop = 20;
        public const ushort StandingSplitRotationalReverseChop = 21;
        public const ushort StandingStabilityReverseChop = 22;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

