#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile ExdDataUnits type as an enum
    /// </summary>
    public enum ExdDataUnits : byte
    {
        NoUnits = 0,
        Laps = 1,
        MilesPerHour = 2,
        KilometersPerHour = 3,
        FeetPerHour = 4,
        MetersPerHour = 5,
        DegreesCelsius = 6,
        DegreesFarenheit = 7,
        Zone = 8,
        Gear = 9,
        Rpm = 10,
        Bpm = 11,
        Degrees = 12,
        Millimeters = 13,
        Meters = 14,
        Kilometers = 15,
        Feet = 16,
        Yards = 17,
        Kilofeet = 18,
        Miles = 19,
        Time = 20,
        EnumTurnType = 21,
        Percent = 22,
        Watts = 23,
        WattsPerKilogram = 24,
        EnumBatteryStatus = 25,
        EnumBikeLightBeamAngleMode = 26,
        EnumBikeLightBatteryStatus = 27,
        EnumBikeLightNetworkConfigType = 28,
        Lights = 29,
        Seconds = 30,
        Minutes = 31,
        Hours = 32,
        Calories = 33,
        Kilojoules = 34,
        Milliseconds = 35,
        SecondPerMile = 36,
        SecondPerKilometer = 37,
        Centimeter = 38,
        EnumCoursePoint = 39,
        Bradians = 40,
        EnumSport = 41,
        InchesHg = 42,
        MmHg = 43,
        Mbars = 44,
        HectoPascals = 45,
        FeetPerMin = 46,
        MetersPerMin = 47,
        MetersPerSec = 48,
        EightCardinal = 49,
        Invalid = 0xFF


    }
}

