#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin Canada Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.67Release
// Tag = production/akw/21.67.00-0-gd790f76b
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile ExdDescriptors type as an enum
    /// </summary>
    public enum ExdDescriptors : byte
    {
        BikeLightBatteryStatus = 0,
        BeamAngleStatus = 1,
        BateryLevel = 2,
        LightNetworkMode = 3,
        NumberLightsConnected = 4,
        Cadence = 5,
        Distance = 6,
        EstimatedTimeOfArrival = 7,
        Heading = 8,
        Time = 9,
        BatteryLevel = 10,
        TrainerResistance = 11,
        TrainerTargetPower = 12,
        TimeSeated = 13,
        TimeStanding = 14,
        Elevation = 15,
        Grade = 16,
        Ascent = 17,
        Descent = 18,
        VerticalSpeed = 19,
        Di2BatteryLevel = 20,
        FrontGear = 21,
        RearGear = 22,
        GearRatio = 23,
        HeartRate = 24,
        HeartRateZone = 25,
        TimeInHeartRateZone = 26,
        HeartRateReserve = 27,
        Calories = 28,
        GpsAccuracy = 29,
        GpsSignalStrength = 30,
        Temperature = 31,
        TimeOfDay = 32,
        Balance = 33,
        PedalSmoothness = 34,
        Power = 35,
        FunctionalThresholdPower = 36,
        IntensityFactor = 37,
        Work = 38,
        PowerRatio = 39,
        NormalizedPower = 40,
        TrainingStressScore = 41,
        TimeOnZone = 42,
        Speed = 43,
        Laps = 44,
        Reps = 45,
        WorkoutStep = 46,
        CourseDistance = 47,
        NavigationDistance = 48,
        CourseEstimatedTimeOfArrival = 49,
        NavigationEstimatedTimeOfArrival = 50,
        CourseTime = 51,
        NavigationTime = 52,
        CourseHeading = 53,
        NavigationHeading = 54,
        PowerZone = 55,
        TorqueEffectiveness = 56,
        TimerTime = 57,
        PowerWeightRatio = 58,
        LeftPlatformCenterOffset = 59,
        RightPlatformCenterOffset = 60,
        LeftPowerPhaseStartAngle = 61,
        RightPowerPhaseStartAngle = 62,
        LeftPowerPhaseFinishAngle = 63,
        RightPowerPhaseFinishAngle = 64,
        Gears = 65,
        Pace = 66,
        TrainingEffect = 67,
        VerticalOscillation = 68,
        VerticalRatio = 69,
        GroundContactTime = 70,
        LeftGroundContactTimeBalance = 71,
        RightGroundContactTimeBalance = 72,
        StrideLength = 73,
        RunningCadence = 74,
        PerformanceCondition = 75,
        CourseType = 76,
        TimeInPowerZone = 77,
        NavigationTurn = 78,
        CourseLocation = 79,
        NavigationLocation = 80,
        Compass = 81,
        GearCombo = 82,
        MuscleOxygen = 83,
        Icon = 84,
        CompassHeading = 85,
        GpsHeading = 86,
        GpsElevation = 87,
        AnaerobicTrainingEffect = 88,
        Course = 89,
        OffCourse = 90,
        GlideRatio = 91,
        VerticalDistance = 92,
        Vmg = 93,
        AmbientPressure = 94,
        Pressure = 95,
        Vam = 96,
        Invalid = 0xFF


    }
}

