#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.105Release
// Tag = production/release/21.105.00-0-gdc65d24
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile ExdQualifiers type as an enum
    /// </summary>
    public enum ExdQualifiers : byte
    {
        NoQualifier = 0,
        Instantaneous = 1,
        Average = 2,
        Lap = 3,
        Maximum = 4,
        MaximumAverage = 5,
        MaximumLap = 6,
        LastLap = 7,
        AverageLap = 8,
        ToDestination = 9,
        ToGo = 10,
        ToNext = 11,
        NextCoursePoint = 12,
        Total = 13,
        ThreeSecondAverage = 14,
        TenSecondAverage = 15,
        ThirtySecondAverage = 16,
        PercentMaximum = 17,
        PercentMaximumAverage = 18,
        LapPercentMaximum = 19,
        Elapsed = 20,
        Sunrise = 21,
        Sunset = 22,
        ComparedToVirtualPartner = 23,
        Maximum24h = 24,
        Minimum24h = 25,
        Minimum = 26,
        First = 27,
        Second = 28,
        Third = 29,
        Shifter = 30,
        LastSport = 31,
        Moving = 32,
        Stopped = 33,
        EstimatedTotal = 34,
        Zone9 = 242,
        Zone8 = 243,
        Zone7 = 244,
        Zone6 = 245,
        Zone5 = 246,
        Zone4 = 247,
        Zone3 = 248,
        Zone2 = 249,
        Zone1 = 250,
        Invalid = 0xFF


    }
}

