#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.105Release
// Tag = production/release/21.105.00-0-gdc65d24
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile HipStabilityExerciseName type as a class
    /// </summary>
    public static class HipStabilityExerciseName 
    {
        public const ushort BandSideLyingLegRaise = 0;
        public const ushort DeadBug = 1;
        public const ushort WeightedDeadBug = 2;
        public const ushort ExternalHipRaise = 3;
        public const ushort WeightedExternalHipRaise = 4;
        public const ushort FireHydrantKicks = 5;
        public const ushort WeightedFireHydrantKicks = 6;
        public const ushort HipCircles = 7;
        public const ushort WeightedHipCircles = 8;
        public const ushort InnerThighLift = 9;
        public const ushort WeightedInnerThighLift = 10;
        public const ushort LateralWalksWithBandAtAnkles = 11;
        public const ushort PretzelSideKick = 12;
        public const ushort WeightedPretzelSideKick = 13;
        public const ushort ProneHipInternalRotation = 14;
        public const ushort WeightedProneHipInternalRotation = 15;
        public const ushort Quadruped = 16;
        public const ushort QuadrupedHipExtension = 17;
        public const ushort WeightedQuadrupedHipExtension = 18;
        public const ushort QuadrupedWithLegLift = 19;
        public const ushort WeightedQuadrupedWithLegLift = 20;
        public const ushort SideLyingLegRaise = 21;
        public const ushort WeightedSideLyingLegRaise = 22;
        public const ushort SlidingHipAdduction = 23;
        public const ushort WeightedSlidingHipAdduction = 24;
        public const ushort StandingAdduction = 25;
        public const ushort WeightedStandingAdduction = 26;
        public const ushort StandingCableHipAbduction = 27;
        public const ushort StandingHipAbduction = 28;
        public const ushort WeightedStandingHipAbduction = 29;
        public const ushort StandingRearLegRaise = 30;
        public const ushort WeightedStandingRearLegRaise = 31;
        public const ushort SupineHipInternalRotation = 32;
        public const ushort WeightedSupineHipInternalRotation = 33;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

