#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.105Release
// Tag = production/release/21.105.00-0-gdc65d24
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile LanguageBits4 type as a class
    /// </summary>
    public static class LanguageBits4 
    {
        public const byte BrazilianPortuguese = 0x01;
        public const byte Indonesian = 0x02;
        public const byte Malaysian = 0x04;
        public const byte Vietnamese = 0x08;
        public const byte Burmese = 0x10;
        public const byte Mongolian = 0x20;
        public const byte Invalid = (byte)0x00;


    }
}

