#region Copyright
///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile OlympicLiftExerciseName type as a class
    /// </summary>
    public static class OlympicLiftExerciseName 
    {
        public const ushort BarbellHangPowerClean = 0;
        public const ushort BarbellHangSquatClean = 1;
        public const ushort BarbellPowerClean = 2;
        public const ushort BarbellPowerSnatch = 3;
        public const ushort BarbellSquatClean = 4;
        public const ushort CleanAndJerk = 5;
        public const ushort BarbellHangPowerSnatch = 6;
        public const ushort BarbellHangPull = 7;
        public const ushort BarbellHighPull = 8;
        public const ushort BarbellSnatch = 9;
        public const ushort BarbellSplitJerk = 10;
        public const ushort Clean = 11;
        public const ushort DumbbellClean = 12;
        public const ushort DumbbellHangPull = 13;
        public const ushort OneHandDumbbellSplitSnatch = 14;
        public const ushort PushJerk = 15;
        public const ushort SingleArmDumbbellSnatch = 16;
        public const ushort SingleArmHangSnatch = 17;
        public const ushort SingleArmKettlebellSnatch = 18;
        public const ushort SplitJerk = 19;
        public const ushort SquatCleanAndJerk = 20;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

