#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin Canada Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.67Release
// Tag = production/akw/21.67.00-0-gd790f76b
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile PushUpExerciseName type as a class
    /// </summary>
    public static class PushUpExerciseName 
    {
        public const ushort ChestPressWithBand = 0;
        public const ushort AlternatingStaggeredPushUp = 1;
        public const ushort WeightedAlternatingStaggeredPushUp = 2;
        public const ushort AlternatingHandsMedicineBallPushUp = 3;
        public const ushort WeightedAlternatingHandsMedicineBallPushUp = 4;
        public const ushort BosuBallPushUp = 5;
        public const ushort WeightedBosuBallPushUp = 6;
        public const ushort ClappingPushUp = 7;
        public const ushort WeightedClappingPushUp = 8;
        public const ushort CloseGripMedicineBallPushUp = 9;
        public const ushort WeightedCloseGripMedicineBallPushUp = 10;
        public const ushort CloseHandsPushUp = 11;
        public const ushort WeightedCloseHandsPushUp = 12;
        public const ushort DeclinePushUp = 13;
        public const ushort WeightedDeclinePushUp = 14;
        public const ushort DiamondPushUp = 15;
        public const ushort WeightedDiamondPushUp = 16;
        public const ushort ExplosiveCrossoverPushUp = 17;
        public const ushort WeightedExplosiveCrossoverPushUp = 18;
        public const ushort ExplosivePushUp = 19;
        public const ushort WeightedExplosivePushUp = 20;
        public const ushort FeetElevatedSideToSidePushUp = 21;
        public const ushort WeightedFeetElevatedSideToSidePushUp = 22;
        public const ushort HandReleasePushUp = 23;
        public const ushort WeightedHandReleasePushUp = 24;
        public const ushort HandstandPushUp = 25;
        public const ushort WeightedHandstandPushUp = 26;
        public const ushort InclinePushUp = 27;
        public const ushort WeightedInclinePushUp = 28;
        public const ushort IsometricExplosivePushUp = 29;
        public const ushort WeightedIsometricExplosivePushUp = 30;
        public const ushort JudoPushUp = 31;
        public const ushort WeightedJudoPushUp = 32;
        public const ushort KneelingPushUp = 33;
        public const ushort WeightedKneelingPushUp = 34;
        public const ushort MedicineBallChestPass = 35;
        public const ushort MedicineBallPushUp = 36;
        public const ushort WeightedMedicineBallPushUp = 37;
        public const ushort OneArmPushUp = 38;
        public const ushort WeightedOneArmPushUp = 39;
        public const ushort WeightedPushUp = 40;
        public const ushort PushUpAndRow = 41;
        public const ushort WeightedPushUpAndRow = 42;
        public const ushort PushUpPlus = 43;
        public const ushort WeightedPushUpPlus = 44;
        public const ushort PushUpWithFeetOnSwissBall = 45;
        public const ushort WeightedPushUpWithFeetOnSwissBall = 46;
        public const ushort PushUpWithOneHandOnMedicineBall = 47;
        public const ushort WeightedPushUpWithOneHandOnMedicineBall = 48;
        public const ushort ShoulderPushUp = 49;
        public const ushort WeightedShoulderPushUp = 50;
        public const ushort SingleArmMedicineBallPushUp = 51;
        public const ushort WeightedSingleArmMedicineBallPushUp = 52;
        public const ushort SpidermanPushUp = 53;
        public const ushort WeightedSpidermanPushUp = 54;
        public const ushort StackedFeetPushUp = 55;
        public const ushort WeightedStackedFeetPushUp = 56;
        public const ushort StaggeredHandsPushUp = 57;
        public const ushort WeightedStaggeredHandsPushUp = 58;
        public const ushort SuspendedPushUp = 59;
        public const ushort WeightedSuspendedPushUp = 60;
        public const ushort SwissBallPushUp = 61;
        public const ushort WeightedSwissBallPushUp = 62;
        public const ushort SwissBallPushUpPlus = 63;
        public const ushort WeightedSwissBallPushUpPlus = 64;
        public const ushort TPushUp = 65;
        public const ushort WeightedTPushUp = 66;
        public const ushort TripleStopPushUp = 67;
        public const ushort WeightedTripleStopPushUp = 68;
        public const ushort WideHandsPushUp = 69;
        public const ushort WeightedWideHandsPushUp = 70;
        public const ushort ParalletteHandstandPushUp = 71;
        public const ushort WeightedParalletteHandstandPushUp = 72;
        public const ushort RingHandstandPushUp = 73;
        public const ushort WeightedRingHandstandPushUp = 74;
        public const ushort RingPushUp = 75;
        public const ushort WeightedRingPushUp = 76;
        public const ushort PushUp = 77;
        public const ushort PilatesPushup = 78;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

