#region Copyright
///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile SportBits5 type as a class
    /// </summary>
    public static class SportBits5 
    {
        public const byte WaterSkiing = 0x01;
        public const byte Kayaking = 0x02;
        public const byte Rafting = 0x04;
        public const byte Windsurfing = 0x08;
        public const byte Kitesurfing = 0x10;
        public const byte Tactical = 0x20;
        public const byte Jumpmaster = 0x40;
        public const byte Boxing = 0x80;
        public const byte Invalid = (byte)0x00;


    }
}

