#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.105Release
// Tag = production/release/21.105.00-0-gdc65d24
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile SportBits1 type as a class
    /// </summary>
    public static class SportBits1 
    {
        public const byte Tennis = 0x01;
        public const byte AmericanFootball = 0x02;
        public const byte Training = 0x04;
        public const byte Walking = 0x08;
        public const byte CrossCountrySkiing = 0x10;
        public const byte AlpineSkiing = 0x20;
        public const byte Snowboarding = 0x40;
        public const byte Rowing = 0x80;
        public const byte Invalid = (byte)0x00;


    }
}

