#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.101Release
// Tag = production/release/21.101.00-0-gceb92d5
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile SportBits4 type as a class
    /// </summary>
    public static class SportBits4 
    {
        public const byte Sailing = 0x01;
        public const byte IceSkating = 0x02;
        public const byte SkyDiving = 0x04;
        public const byte Snowshoeing = 0x08;
        public const byte Snowmobiling = 0x10;
        public const byte StandUpPaddleboarding = 0x20;
        public const byte Surfing = 0x40;
        public const byte Wakeboarding = 0x80;
        public const byte Invalid = (byte)0x00;


    }
}

