#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.101Release
// Tag = production/release/21.101.00-0-gceb92d5
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile TimeZone type as an enum
    /// </summary>
    public enum TimeZone : byte
    {
        Almaty = 0,
        Bangkok = 1,
        Bombay = 2,
        Brasilia = 3,
        Cairo = 4,
        CapeVerdeIs = 5,
        Darwin = 6,
        Eniwetok = 7,
        Fiji = 8,
        HongKong = 9,
        Islamabad = 10,
        Kabul = 11,
        Magadan = 12,
        MidAtlantic = 13,
        Moscow = 14,
        Muscat = 15,
        Newfoundland = 16,
        Samoa = 17,
        Sydney = 18,
        Tehran = 19,
        Tokyo = 20,
        UsAlaska = 21,
        UsAtlantic = 22,
        UsCentral = 23,
        UsEastern = 24,
        UsHawaii = 25,
        UsMountain = 26,
        UsPacific = 27,
        Other = 28,
        Auckland = 29,
        Kathmandu = 30,
        EuropeWesternWet = 31,
        EuropeCentralCet = 32,
        EuropeEasternEet = 33,
        Jakarta = 34,
        Perth = 35,
        Adelaide = 36,
        Brisbane = 37,
        Tasmania = 38,
        Iceland = 39,
        Amsterdam = 40,
        Athens = 41,
        Barcelona = 42,
        Berlin = 43,
        Brussels = 44,
        Budapest = 45,
        Copenhagen = 46,
        Dublin = 47,
        Helsinki = 48,
        Lisbon = 49,
        London = 50,
        Madrid = 51,
        Munich = 52,
        Oslo = 53,
        Paris = 54,
        Prague = 55,
        Reykjavik = 56,
        Rome = 57,
        Stockholm = 58,
        Vienna = 59,
        Warsaw = 60,
        Zurich = 61,
        Quebec = 62,
        Ontario = 63,
        Manitoba = 64,
        Saskatchewan = 65,
        Alberta = 66,
        BritishColumbia = 67,
        Boise = 68,
        Boston = 69,
        Chicago = 70,
        Dallas = 71,
        Denver = 72,
        KansasCity = 73,
        LasVegas = 74,
        LosAngeles = 75,
        Miami = 76,
        Minneapolis = 77,
        NewYork = 78,
        NewOrleans = 79,
        Phoenix = 80,
        SantaFe = 81,
        Seattle = 82,
        WashingtonDc = 83,
        UsArizona = 84,
        Chita = 85,
        Ekaterinburg = 86,
        Irkutsk = 87,
        Kaliningrad = 88,
        Krasnoyarsk = 89,
        Novosibirsk = 90,
        PetropavlovskKamchatskiy = 91,
        Samara = 92,
        Vladivostok = 93,
        MexicoCentral = 94,
        MexicoMountain = 95,
        MexicoPacific = 96,
        CapeTown = 97,
        Winkhoek = 98,
        Lagos = 99,
        Riyahd = 100,
        Venezuela = 101,
        AustraliaLh = 102,
        Santiago = 103,
        Manual = 253,
        Automatic = 254,
        Invalid = 0xFF


    }
}

