#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.105Release
// Tag = production/release/21.105.00-0-gdc65d24
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile TotalBodyExerciseName type as a class
    /// </summary>
    public static class TotalBodyExerciseName 
    {
        public const ushort Burpee = 0;
        public const ushort WeightedBurpee = 1;
        public const ushort BurpeeBoxJump = 2;
        public const ushort WeightedBurpeeBoxJump = 3;
        public const ushort HighPullBurpee = 4;
        public const ushort ManMakers = 5;
        public const ushort OneArmBurpee = 6;
        public const ushort SquatThrusts = 7;
        public const ushort WeightedSquatThrusts = 8;
        public const ushort SquatPlankPushUp = 9;
        public const ushort WeightedSquatPlankPushUp = 10;
        public const ushort StandingTRotationBalance = 11;
        public const ushort WeightedStandingTRotationBalance = 12;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

