#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile WktStepTarget type as an enum
    /// </summary>
    public enum WktStepTarget : byte
    {
        Speed = 0,
        HeartRate = 1,
        Open = 2,
        Cadence = 3,
        Power = 4,
        Grade = 5,
        Resistance = 6,
        Power3s = 7,
        Power10s = 8,
        Power30s = 9,
        PowerLap = 10,
        SwimStroke = 11,
        SpeedLap = 12,
        HeartRateLap = 13,
        Invalid = 0xFF


    }
}

