#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin Canada Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.67Release
// Tag = production/akw/21.67.00-0-gd790f76b
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile WktStepTarget type as an enum
    /// </summary>
    public enum WktStepTarget : byte
    {
        Speed = 0,
        HeartRate = 1,
        Open = 2,
        Cadence = 3,
        Power = 4,
        Grade = 5,
        Resistance = 6,
        Power3s = 7,
        Power10s = 8,
        Power30s = 9,
        PowerLap = 10,
        SwimStroke = 11,
        SpeedLap = 12,
        HeartRateLap = 13,
        Invalid = 0xFF


    }
}

