#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin Canada Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.67Release
// Tag = production/akw/21.67.00-0-gd790f76b
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile ActivitySubtype type as an enum
    /// </summary>
    public enum ActivitySubtype : byte
    {
        Generic = 0,
        Treadmill = 1,
        Street = 2,
        Trail = 3,
        Track = 4,
        Spin = 5,
        IndoorCycling = 6,
        Road = 7,
        Mountain = 8,
        Downhill = 9,
        Recumbent = 10,
        Cyclocross = 11,
        HandCycling = 12,
        TrackCycling = 13,
        IndoorRowing = 14,
        Elliptical = 15,
        StairClimbing = 16,
        LapSwimming = 17,
        OpenWater = 18,
        All = 254,
        Invalid = 0xFF


    }
}

