#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile AutolapTrigger type as an enum
    /// </summary>
    public enum AutolapTrigger : byte
    {
        Time = 0,
        Distance = 1,
        PositionStart = 2,
        PositionLap = 3,
        PositionWaypoint = 4,
        PositionMarked = 5,
        Off = 6,
        Invalid = 0xFF


    }
}

