#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.101Release
// Tag = production/release/21.101.00-0-gceb92d5
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile ExdLayout type as an enum
    /// </summary>
    public enum ExdLayout : byte
    {
        FullScreen = 0,
        HalfVertical = 1,
        HalfHorizontal = 2,
        HalfVerticalRightSplit = 3,
        HalfHorizontalBottomSplit = 4,
        FullQuarterSplit = 5,
        HalfVerticalLeftSplit = 6,
        HalfHorizontalTopSplit = 7,
        Dynamic = 8,
        Invalid = 0xFF


    }
}

