#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin Canada Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.67Release
// Tag = production/akw/21.67.00-0-gd790f76b
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile HipRaiseExerciseName type as a class
    /// </summary>
    public static class HipRaiseExerciseName 
    {
        public const ushort BarbellHipThrustOnFloor = 0;
        public const ushort BarbellHipThrustWithBench = 1;
        public const ushort BentKneeSwissBallReverseHipRaise = 2;
        public const ushort WeightedBentKneeSwissBallReverseHipRaise = 3;
        public const ushort BridgeWithLegExtension = 4;
        public const ushort WeightedBridgeWithLegExtension = 5;
        public const ushort ClamBridge = 6;
        public const ushort FrontKickTabletop = 7;
        public const ushort WeightedFrontKickTabletop = 8;
        public const ushort HipExtensionAndCross = 9;
        public const ushort WeightedHipExtensionAndCross = 10;
        public const ushort HipRaise = 11;
        public const ushort WeightedHipRaise = 12;
        public const ushort HipRaiseWithFeetOnSwissBall = 13;
        public const ushort WeightedHipRaiseWithFeetOnSwissBall = 14;
        public const ushort HipRaiseWithHeadOnBosuBall = 15;
        public const ushort WeightedHipRaiseWithHeadOnBosuBall = 16;
        public const ushort HipRaiseWithHeadOnSwissBall = 17;
        public const ushort WeightedHipRaiseWithHeadOnSwissBall = 18;
        public const ushort HipRaiseWithKneeSqueeze = 19;
        public const ushort WeightedHipRaiseWithKneeSqueeze = 20;
        public const ushort InclineRearLegExtension = 21;
        public const ushort WeightedInclineRearLegExtension = 22;
        public const ushort KettlebellSwing = 23;
        public const ushort MarchingHipRaise = 24;
        public const ushort WeightedMarchingHipRaise = 25;
        public const ushort MarchingHipRaiseWithFeetOnASwissBall = 26;
        public const ushort WeightedMarchingHipRaiseWithFeetOnASwissBall = 27;
        public const ushort ReverseHipRaise = 28;
        public const ushort WeightedReverseHipRaise = 29;
        public const ushort SingleLegHipRaise = 30;
        public const ushort WeightedSingleLegHipRaise = 31;
        public const ushort SingleLegHipRaiseWithFootOnBench = 32;
        public const ushort WeightedSingleLegHipRaiseWithFootOnBench = 33;
        public const ushort SingleLegHipRaiseWithFootOnBosuBall = 34;
        public const ushort WeightedSingleLegHipRaiseWithFootOnBosuBall = 35;
        public const ushort SingleLegHipRaiseWithFootOnFoamRoller = 36;
        public const ushort WeightedSingleLegHipRaiseWithFootOnFoamRoller = 37;
        public const ushort SingleLegHipRaiseWithFootOnMedicineBall = 38;
        public const ushort WeightedSingleLegHipRaiseWithFootOnMedicineBall = 39;
        public const ushort SingleLegHipRaiseWithHeadOnBosuBall = 40;
        public const ushort WeightedSingleLegHipRaiseWithHeadOnBosuBall = 41;
        public const ushort WeightedClamBridge = 42;
        public const ushort SingleLegSwissBallHipRaiseAndLegCurl = 43;
        public const ushort Clams = 44;
        public const ushort InnerThighCircles = 45; // Deprecated do not use
        public const ushort InnerThighSideLift = 46; // Deprecated do not use
        public const ushort LegCircles = 47;
        public const ushort LegLift = 48;
        public const ushort LegLiftInExternalRotation = 49;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

