#region Copyright
///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile HyperextensionExerciseName type as a class
    /// </summary>
    public static class HyperextensionExerciseName 
    {
        public const ushort BackExtensionWithOppositeArmAndLegReach = 0;
        public const ushort WeightedBackExtensionWithOppositeArmAndLegReach = 1;
        public const ushort BaseRotations = 2;
        public const ushort WeightedBaseRotations = 3;
        public const ushort BentKneeReverseHyperextension = 4;
        public const ushort WeightedBentKneeReverseHyperextension = 5;
        public const ushort HollowHoldAndRoll = 6;
        public const ushort WeightedHollowHoldAndRoll = 7;
        public const ushort Kicks = 8;
        public const ushort WeightedKicks = 9;
        public const ushort KneeRaises = 10;
        public const ushort WeightedKneeRaises = 11;
        public const ushort KneelingSuperman = 12;
        public const ushort WeightedKneelingSuperman = 13;
        public const ushort LatPullDownWithRow = 14;
        public const ushort MedicineBallDeadliftToReach = 15;
        public const ushort OneArmOneLegRow = 16;
        public const ushort OneArmRowWithBand = 17;
        public const ushort OverheadLungeWithMedicineBall = 18;
        public const ushort PlankKneeTucks = 19;
        public const ushort WeightedPlankKneeTucks = 20;
        public const ushort SideStep = 21;
        public const ushort WeightedSideStep = 22;
        public const ushort SingleLegBackExtension = 23;
        public const ushort WeightedSingleLegBackExtension = 24;
        public const ushort SpineExtension = 25;
        public const ushort WeightedSpineExtension = 26;
        public const ushort StaticBackExtension = 27;
        public const ushort WeightedStaticBackExtension = 28;
        public const ushort SupermanFromFloor = 29;
        public const ushort WeightedSupermanFromFloor = 30;
        public const ushort SwissBallBackExtension = 31;
        public const ushort WeightedSwissBallBackExtension = 32;
        public const ushort SwissBallHyperextension = 33;
        public const ushort WeightedSwissBallHyperextension = 34;
        public const ushort SwissBallOppositeArmAndLegLift = 35;
        public const ushort WeightedSwissBallOppositeArmAndLegLift = 36;
        public const ushort SupermanOnSwissBall = 37;
        public const ushort Cobra = 38;
        public const ushort SupineFloorBarre = 39; // Deprecated do not use
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

