#region Copyright
///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile Language type as an enum
    /// </summary>
    public enum Language : byte
    {
        English = 0,
        French = 1,
        Italian = 2,
        German = 3,
        Spanish = 4,
        Croatian = 5,
        Czech = 6,
        Danish = 7,
        Dutch = 8,
        Finnish = 9,
        Greek = 10,
        Hungarian = 11,
        Norwegian = 12,
        Polish = 13,
        Portuguese = 14,
        Slovakian = 15,
        Slovenian = 16,
        Swedish = 17,
        Russian = 18,
        Turkish = 19,
        Latvian = 20,
        Ukrainian = 21,
        Arabic = 22,
        Farsi = 23,
        Bulgarian = 24,
        Romanian = 25,
        Chinese = 26,
        Japanese = 27,
        Korean = 28,
        Taiwanese = 29,
        Thai = 30,
        Hebrew = 31,
        BrazilianPortuguese = 32,
        Indonesian = 33,
        Malaysian = 34,
        Vietnamese = 35,
        Burmese = 36,
        Mongolian = 37,
        Custom = 254,
        Invalid = 0xFF


    }
}

