#region Copyright
///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile LanguageBits1 type as a class
    /// </summary>
    public static class LanguageBits1 
    {
        public const byte Dutch = 0x01;
        public const byte Finnish = 0x02;
        public const byte Greek = 0x04;
        public const byte Hungarian = 0x08;
        public const byte Norwegian = 0x10;
        public const byte Polish = 0x20;
        public const byte Portuguese = 0x40;
        public const byte Slovakian = 0x80;
        public const byte Invalid = (byte)0x00;


    }
}

