#region Copyright
///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile SubSport type as an enum
    /// </summary>
    public enum SubSport : byte
    {
        Generic = 0,
        Treadmill = 1,
        Street = 2,
        Trail = 3,
        Track = 4,
        Spin = 5,
        IndoorCycling = 6,
        Road = 7,
        Mountain = 8,
        Downhill = 9,
        Recumbent = 10,
        Cyclocross = 11,
        HandCycling = 12,
        TrackCycling = 13,
        IndoorRowing = 14,
        Elliptical = 15,
        StairClimbing = 16,
        LapSwimming = 17,
        OpenWater = 18,
        FlexibilityTraining = 19,
        StrengthTraining = 20,
        WarmUp = 21,
        Match = 22,
        Exercise = 23,
        Challenge = 24,
        IndoorSkiing = 25,
        CardioTraining = 26,
        IndoorWalking = 27,
        EBikeFitness = 28,
        Bmx = 29,
        CasualWalking = 30,
        SpeedWalking = 31,
        BikeToRunTransition = 32,
        RunToBikeTransition = 33,
        SwimToBikeTransition = 34,
        Atv = 35,
        Motocross = 36,
        Backcountry = 37,
        Resort = 38,
        RcDrone = 39,
        Wingsuit = 40,
        Whitewater = 41,
        SkateSkiing = 42,
        Yoga = 43,
        Pilates = 44,
        IndoorRunning = 45,
        GravelCycling = 46,
        EBikeMountain = 47,
        Commuting = 48,
        MixedSurface = 49,
        Navigate = 50,
        TrackMe = 51,
        Map = 52,
        SingleGasDiving = 53,
        MultiGasDiving = 54,
        GaugeDiving = 55,
        ApneaDiving = 56,
        ApneaHunting = 57,
        VirtualActivity = 58,
        Obstacle = 59,
        Breathing = 62,
        SailRace = 65,
        Ultra = 67,
        IndoorClimbing = 68,
        Bouldering = 69,
        All = 254,
        Invalid = 0xFF


    }
}

