name: 'Publish UI Distribution'
description: 'Publishes the UI Distribution'
inputs:
  dotnet-version:
    description: 'Version of dotnet to install'
    required: true
  framework:
    description: 'DotNet Framework'
    required: true
  os:
    description: 'The OS we are running on'
    required: true
outputs:
  artifact:
    description: 'Path to the published artifact'
    value: ${{ github.workspace }}/dist/${{ inputs.os }}-ui
runs:
  using: "composite"
  steps:
    - name: Setup .NET Core SDK ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install MAUI Workloads
      run: dotnet workload install maui-desktop --ignore-failed-sources # TODO: change back to generic "maui" instead of "maui-desktop" to install deps for all platforms
      shell: pwsh

    - name: Prepare env
      run: |
          echo "BUILD_VERSION=$Env:GITHUB_RUN_NUMBER-$Env:GITHUB_RUN_ID" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "RUNNER_TOOL_CACHE=$Env:RUNNER_TOOL_CACHE" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
          
    - name: Publish ${{ inputs.os }}
      run: dotnet publish ${{ github.workspace }}/src/ClientUI/ClientUI.csproj -c Release -f ${{ inputs.framework }} -p:RuntimeIdentifierOverride=${{ inputs.os }} -p:PublishSingleFile=true -p:SelfContained=true
      shell: pwsh

    - name: Copy Config to Distro
      run: Copy-Item ${{ github.workspace }}/configuration.example.json -Destination ${{ github.workspace }}/src/ClientUI/bin/Release/${{ inputs.framework }}/${{ inputs.os }}
      shell: pwsh

    - name: Rename Config
      run: Rename-Item ${{ github.workspace }}/src/ClientUI/bin/Release/${{ inputs.framework }}/${{ inputs.os }}/configuration.example.json -NewName configuration.local.json
      shell: pwsh

    - name: Remove nested Publish Dir
      run: Remove-Item ${{ github.workspace }}/src/ClientUI/bin/Release/${{ inputs.framework }}/${{ inputs.os }}/publish -Recurse
      shell: pwsh

    # Create Build Artifact
    - name: Upload Artifact ui_${{ inputs.os }}_${{ env.BUILD_VERSION }}
      uses: actions/upload-artifact@v3
      with:
        name: ui_${{ inputs.os }}_${{ env.BUILD_VERSION }}
        path: ${{ github.workspace }}/src/ClientUI/bin/Release/${{ inputs.framework }}/${{ inputs.os }}