name: 'Publish UI Distribution'
description: 'Publishes the UI Distribution'
inputs:
  dotnet-version:
    description: 'Version of dotnet to install'
    required: true
  framework:
    description: 'DotNet Framework'
    required: true
  os:
    description: 'The OS we are running on'
    required: true
outputs:
  artifact_name:
    description: 'Name of the uploaded artifact'
    value: ui_${{ inputs.os }}_${{ github.run_number }}-${{ github.run_id }}
runs:
  using: "composite"
  steps:
    - name: Setup .NET Core SDK ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore MAUI Workloads
      run: dotnet workload restore
      shell: pwsh

    - name: List MAUI Workloads
      run: dotnet workload list
      shell: pwsh

    - name: Prepare env
      run: |
          echo "BUILD_VERSION=$Env:GITHUB_RUN_NUMBER-$Env:GITHUB_RUN_ID" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "RUNNER_TOOL_CACHE=$Env:RUNNER_TOOL_CACHE" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    # dotnet publish src/ClientUI/ClientUI.csproj -c Release -f net7.0-windows10.0.19041.0 -p:RuntimeIdentifierOverride=win10-x64 -p:PublishSingleFile=true -p:SelfContained=true
    - name: Publish ${{ inputs.os }}
      run: dotnet publish ${{ github.workspace }}/src/ClientUI/ClientUI.csproj -c Release -f ${{ inputs.framework }} -p:RuntimeIdentifierOverride=${{ inputs.os }} -p:PublishSingleFile=true -p:SelfContained=true
      shell: pwsh

    - name: Rename Config
      run: Rename-Item ${{ github.workspace }}/src/ClientUI/bin/Release/${{ inputs.framework }}/${{ inputs.os }}/configuration.example.json -NewName configuration.local.json
      shell: pwsh

    - name: Remove nested Publish Dir
      run: Remove-Item ${{ github.workspace }}/src/ClientUI/bin/Release/${{ inputs.framework }}/${{ inputs.os }}/publish -Recurse
      shell: pwsh

    # Create Build Artifact
    - name: Upload Artifact ui_${{ inputs.os }}_${{ github.run_number }}-${{ github.run_id }}
      uses: actions/upload-artifact@v4
      with:
        name: ui_${{ inputs.os }}_${{ github.run_number }}-${{ github.run_id }}
        path: ${{ github.workspace }}/src/ClientUI/bin/Release/${{ inputs.framework }}/${{ inputs.os }}


# Installed Workload Id      Manifest Version       Installation Source
# ---------------------------------------------------------------------
# maui-android               7.0.92/7.0.100         VS 17.7.34031.279
# android                    33.0.68/7.0.100        VS 17.7.34031.279
# ios                        16.4.7098/7.0.100      VS 17.7.34031.279
# maui-ios                   7.0.92/7.0.100         VS 17.7.34031.279
# maui-windows               7.0.92/7.0.100         VS 17.7.34031.279
# maui-maccatalyst           7.0.92/7.0.100         VS 17.7.34031.279
# maccatalyst                16.4.7098/7.0.100      VS 17.7.34031.279
