{
 "title": "Peloton To Garmin",
 "description": "Dashboard for viewing opentel metrics from P2G",
 "tags": [
  "fitness",
  "opentelemetry",
  "logs",
  "tracing",
  "metrics",
  "guest"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "options": {
    "content": "![Image](https://github.com/philosowaffle/peloton-to-garmin/raw/v2/images/logo/readme_banner.png)\r\n"
   }
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_build_info" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_health_info" }
   ]
  },
  {
   "title": "Failed Upload Attempts",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_failed_upload_attempts" }
   ]
  },
  {
   "title": "Total Polls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2g_sync_duration_seconds_count"
    }
   ]
  },
  {
   "title": "FIT Converted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(p2g_workouts_converted{type=~\".+\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"p2g\"}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_build_info" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "targets": [
    { "expr": "p2g_build_info" }
   ]
  },
  {
   "title": "Files to Upload",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_files_to_upload" }
   ]
  },
  {
   "title": "Avg. Sync Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2g_sync_duration_seconds_sum / p2g_sync_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Private Memory Bytes",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_private_memory_bytes{job=\"p2g\"}"
    },
    {}
   ]
  },
  {
   "title": "Available Total Memory ??",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"p2g\"}"
    }
   ]
  },
  {
   "title": "DotNet Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_build_info" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "{app=\"p2g\"} | json",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({app=\"p2g\"} | json [30m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(docker_container_network_in_bytes{job=\"homeservices-docker\", name=\"p2g\"}[$__rate_interval]) * -1",
     "legendFormat": "In"
    },
    {
     "expr": "increase(docker_container_network_out_bytes{job=\"homeservices-docker\", name=\"p2g\"}[$__rate_interval])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"p2g\"}[$__rate_interval])",
     "legendFormat": "Memory in Use"
    }
   ]
  },
  {
   "title": "Working Set Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"p2g\"}",
     "legendFormat": "Memory in Use"
    }
   ]
  },
  {
   "title": "Working Set Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"p2g\"}",
     "legendFormat": "Memory in Use"
    }
   ]
  },
  {
   "title": "Github",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Issues",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      { "options": { "query": "is:issue is:open ", "timeField": 0 }, "owner": "philosowaffle", "repository": "peloton-to-garmin" }
     ]
    },
    {
     "title": "Open PRs",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "targets": [
      { "options": { "gitRef": "v2", "query": " is:open ", "timeField": 1 }, "owner": "philosowaffle", "repository": "peloton-to-garmin" }
     ]
    }
   ]
  }
 ]
}