version: "3.9"

services:
  p2g:
    container_name: p2g
    image: philosowaffle/peloton-to-garmin:console-stable
    environment:
      - TZ=America/Chicago
      - P2G_CONFIG_DIRECTORY=/app/config
    volumes:
      - ./config:/app/config
      - ./output:/app/output
