
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;

namespace Garmin
{
	public static class GarminUploader
	{
		private static string[] ScriptPathParts = new string[] { Environment.CurrentDirectory, "..", "..", "..", "..", "..", "garminUpload.py" };
		private static string ScriptPath = Path.Combine(ScriptPathParts);

		public static bool UploadToGarmin(ICollection<string> filePaths, string garminEmail, string garminPassword, string pathToPythonExe)
		{
			ProcessStartInfo start = new ProcessStartInfo();
			start.FileName = pathToPythonExe;

			var paths = String.Join("-f ", filePaths);
			var cmd = $"{ScriptPath} -ge {garminEmail} -gp {garminPassword} -f {paths}";
			
			start.Arguments = cmd;
			start.UseShellExecute = false;// Do not use OS shell
			start.CreateNoWindow = true; // We don't need new window
			start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
			start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
			using (Process process = Process.Start(start))
			{
				using (StreamReader reader = process.StandardOutput)
				{
					string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
					string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
				}
			}
			return true;
		}
	}
}
