name: 'Installs and Cache DotNet'
description: 'Tries to fetch dotnet from cache, if not found, installs, then caches'
inputs:
  dotnet-version:
    description: 'Version of dotnet to install'
    required: true
  os:
    description: 'The OS we are running on'
    required: true
  dotnet-install-dir:
    required: false
    default: '.\.dotnet'
outputs:
  dotnet-path:
    description: "Path to dotnet install"
    value: ${{ inputs.dotnet-install-dir }}
runs:
  using: "composite"
  steps:
    - name: Cache dotnet
      id: cache-dotnet
      uses: actions/cache@v3
      with:
        path: ${{ inputs.dotnet-install-dir }}
        key: ${{ matrix.os }}-${{ matrix.dotnet }}
        restore-keys: ${{ inputs.os }}-${{ inputs.dotnet-version }}

    - name: Install dotnet
      if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Check default dotnet version
      run: dotnet --version

    - name: Set installed/cached dotnet path [${{ inputs.dotnet-install-dir }}]
      run: echo "${{ inputs.dotnet-install-dir }}" | Out-File -FilePath $ENV:GITHUB_PATH -Encoding utf8 -Append

    - name: Check installed/cached dotnet version
      run: dotnet --version
