name: Publish Distro

on:
  workflow_dispatch:
  push:
    branches:
    - fitFiles
    paths:
    - 'src/**'
    - 'python/upload/**'
    - 'UnitTests/**'
    - 'PelotonToGarmin.sln'
    - 'configuration.example.json'

jobs:
  publish:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        dotnet: ['5.0.201']
        os: [ 'win10-x64' ]
        #os: [ 'linux-x64', 'win10-x64', 'osx-x64' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Clean
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear
    
    - name: Restore
      run: dotnet restore
        
    - name: Publish ${{matrix.os}}
      run: dotnet publish ${{ github.workspace }}/src/PelotonToGarminConsole/PelotonToGarminConsole.csproj --no-restore -c Release -r ${{ matrix.os }} -o ${{ github.workspace }}/dist/${{ matrix.os }}

    - name: Copy Config to Distro
      run: cp ${{ github.workspace }}/configuration.example.json ${{ github.workspace }}/dist/${{ matrix.os }}/configuration.local.json

    - name: Copy Python to Distro
      run: cp -R ${{ github.workspace }}/python ${{ github.workspace }}/dist/${{ matrix.os }}
      
    - name: Create Archive ${{ matrix.os }}
      uses: papeloto/action-zip@v1
      with:
       files: /dist/${{ matrix.os }}/
       dest: /dist/${{ matrix.os }}.zip

    - name: Commit changes ${{ matrix.os }}
      uses: EndBug/add-and-commit@v7.0.0
      with:
        message: "Create ${{ matrix.os }} distro"
        add: ${{ github.workspace }}/dist/${{ matrix.os }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
