name: Publish Distro

on:
  workflow_dispatch:
  push:
    branches:
    - v2
    paths:
    - 'src/**'
    - 'python/upload/**'
    - 'PelotonToGarmin.sln'
    - 'configuration.example.json'
    - '.github/workflows/publish_distros.yml'

jobs:
  publish:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        dotnet: ['5.0.201']
        os: [ 'win10-x64', 'osx-x64' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Clean
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear
    
    - name: Restore
      run: dotnet restore
        
    - name: Publish ${{matrix.os}}
      run: dotnet publish ${{ github.workspace }}/src/PelotonToGarminConsole/PelotonToGarminConsole.csproj --no-restore -c Release -r ${{ matrix.os }} -o ${{ github.workspace }}/dist/${{ matrix.os }}

    - name: Copy Config to Distro
      run: cp ${{ github.workspace }}/configuration.example.json ${{ github.workspace }}/dist/${{ matrix.os }}/configuration.local.json

    - name: Copy Python to Distro
      if: ${{ matrix.os == 'win10-x64' }}
      run: cp -R ${{ github.workspace }}/python ${{ github.workspace }}/dist/${{ matrix.os }}
      
    - name: Create Archive ${{ matrix.os }}
      uses: papeloto/action-zip@v1
      with:
       files: /dist/${{ matrix.os }}/
       dest: /dist/${{ matrix.os }}.zip

    - name: Upload Artifact ${{ matrix.os }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: ${{ github.workspace }}/dist/${{ matrix.os }}.zip
