name: Test Artifact Sharing

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:

  publish-ui-dist:
    name: Publish UI Distribution
    runs-on: 'windows-latest'
    outputs:
      artifact_name: ${{ steps.win-ui-create-artifact.outputs.artifact_name }}

    steps:

      - uses: actions/checkout@v4
      - name: Publish UI Distribution
        uses: ./.github/actions/test-action
        id: win-ui-create-artifact
  
  create-gh-release:
    runs-on: ubuntu-latest
    needs: [publish-ui-dist]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.publish-ui-dist.outputs.artifact_name }}
          path: ${{ github.workspace }}/downloaded

      - name: Create Zip for Win UI Release Artifact
        uses: vimtor/action-zip@v1.2
        with:
          files: /downloaded # must be relative to gh workspace, does not support absolute paths :(
          dest: ui_win.zip # this is hardecoded to output to ${{ github.workspace }}/ui_win.zip :(
    
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: my_zipped_artifact
          path: ${{ github.workspace }}/ui_win.zip