site_name: Peloton To Garmin
site_description: Convert workout data from Peloton into JSON/TCX/FIT files that can be uploaded to Garmin Connect
site_author: philosowaffle

repo_url: https://github.com/philosowaffle/peloton-to-garmin
edit_uri: /tree/master/mkdocs/docs

extra:
  version:
    provider: mike

theme:
  name: material
  logo: img/256x256.png
  favicon: img/favicon.ico
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - naviation.sections
    - navigation.indexes

nav:
 - Home: index.md
 - Features: features.md
 - Install:
    - Install: install/index.md
    - Docker: install/docker.md
    - Windows: install/windows.md
    - Source: install/source.md
 - Configuration: 
    - Configuration: configuration/index.md
    - 'User Interface and Json': configuration/json.md
    - Observability: observability.md
 - Help:
    - Help: help.md
    - 'F.A.Q': faq.md
    - Migration: migration/migrations.md
    - Contributing: contributing.md