site_name: Peloton To Garmin
site_description: Convert workout data from Peloton into JSON/TCX/FIT files that can be uploaded to Garmin Connect
site_author: philosowaffle
site_url: 'https://philosowaffle.github.io/peloton-to-garmin/'

repo_url: https://github.com/philosowaffle/peloton-to-garmin
edit_uri: /tree/master/mkdocs/docs

extra:
  version:
    provider: mike

theme:
  name: material
  logo: img/256x256.png
  favicon: img/favicon.ico
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - naviation.sections
    - navigation.indexes
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
 - Home: index.md
 - Features: features.md
 - Install:
    - Install: install/index.md
    - Docker:
      - Docker: install/docker.md
      - 'Web UI': install/docker-webui.md
      - Headless: install/docker-headless.md
    - 'Windows App': install/windows.md
    - Source: install/source.md
    - 'GitHub Actions': install/github-action.md
 - Configuration: 
    - Configuration: configuration/index.md
    - Settings:
      - 'App Settings': configuration/app.md
      - 'Format Settings': configuration/format.md
      - 'Garmin Settings': configuration/garmin.md
      - 'Peloton Settings': configuration/peloton.md
    - 'Low Level Settings':
      - 'Api File Configuration': configuration/api.md
      - 'WebUI File Configuration': configuration/webui.md
      - 'Observability File Configuration': configuration/observability.md
    - 'Exercise Types': configuration/exercise-types.md
 - Help:
    - Help: help.md
    - 'F.A.Q': faq.md
    - Migration: migration/migrations.md
    - Contributing: contributing.md